version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./buildimages/web.dockerfile
    depends_on:
      - db
      - smtp
    working_dir: /odoo-dev/addon
    ports:
      - "8069:8069"
    volumes:
      - odoo-identity-web-data:/var/lib/odoo
      - .:/odoo-dev/addon
    environment:
      - PIP_EXTRA_INDEX_URL
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-identity-db-data:/var/lib/postgresql/data/pgdata
  smtp:
    image: namshi/smtp
    environment:
      - MAILNAME=no-reply-odoo@gwyddiongames.com
volumes:
  odoo-identity-web-data:
  odoo-identity-db-data:
